# Generated by Django 5.2.5 on 2025-08-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0002_media_review_studioroom_savedstudio'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='instant_booking',
            field=models.BooleanField(default=False),
        ),
    ]
